use std::fmt;
use core::cmp::*;
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};



#[derive(Debug, Clone, PartialEq, PartialOrd, Eq, Ord, Hash)]
pub enum Style {
    Typed(Rule),
    Untyped(Untyped),
}

#[derive(Debug, Clone, PartialEq, PartialOrd, Eq, Ord, Hash)]
pub struct Untyped {
    pub property: String,
    pub value: String,
}

///////////////////////////////////////////////////////////////////////////////
// INTERNAL RULES
///////////////////////////////////////////////////////////////////////////////

#[derive(Debug, Clone, PartialEq, PartialOrd, Eq, Ord, Hash)]
pub struct Rule {
    pub property: Property,
    pub value: Value,
}

#[derive(Debug, Clone, PartialEq, PartialOrd, Eq, Ord, Hash)]
pub enum Property {
    AlignContent,
    AlignItems,
    AlignSelf,
    All,
    Animation,
    AnimationDelay,
    AnimationDirection,
    AnimationDuration,
    AnimationFillMode,
    AnimationIterationCount,
    AnimationName,
    AnimationPlayState,
    AnimationTimingFunction,
    Azimuth,
    Background,
    BackgroundAttachment,
    BackgroundBlendMode,
    BackgroundClip,
    BackgroundColor,
    BackgroundImage,
    BackgroundOrigin,
    BackgroundPosition,
    BackgroundRepeat,
    BackgroundSize,
    Border,
    BorderBottom,
    BorderBottomColor,
    BorderBottomLeftRadius,
    BorderBottomRightRadius,
    BorderBottomStyle,
    BorderBottomWidth,
    BorderCollapse,
    BorderColor,
    BorderImage,
    BorderImageOutset,
    BorderImageRepeat,
    BorderImageSlice,
    BorderImageSource,
    BorderImageWidth,
    BorderLeft,
    BorderLeftColor,
    BorderLeftStyle,
    BorderLeftWidth,
    BorderRadius,
    BorderRight,
    BorderRightColor,
    BorderRightStyle,
    BorderRightWidth,
    BorderSpacing,
    BorderStyle,
    BorderTop,
    BorderTopColor,
    BorderTopLeftRadius,
    BorderTopRightRadius,
    BorderTopStyle,
    BorderTopWidth,
    BorderWidth,
    Bottom,
    BoxDecorationBreak,
    BoxShadow,
    BoxSizing,
    BreakAfter,
    BreakBefore,
    BreakInside,
    CaptionSide,
    CaretColor,
    Clear,
    Clip,
    ClipPath,
    ClipRule,
    Color,
    ColorInterpolationFilters,
    ColumnCount,
    ColumnFill,
    ColumnGap,
    ColumnRule,
    ColumnRuleColor,
    ColumnRuleStyle,
    ColumnRuleWidth,
    Columns,
    ColumnSpan,
    ColumnWidth,
    Contain,
    Content,
    CounterIncrement,
    CounterReset,
    Cue,
    CueAfter,
    CueBefore,
    Cursor,
    Direction,
    Display,
    Elevation,
    EmptyCells,
    Filter,
    Flex,
    FlexBasis,
    FlexDirection,
    FlexFlow,
    FlexGrow,
    FlexShrink,
    FlexWrap,
    Float,
    FloodColor,
    FloodOpacity,
    Font,
    FontFamily,
    FontFeatureSettings,
    FontKerning,
    FontSize,
    FontSizeAdjust,
    FontStretch,
    FontStyle,
    FontSynthesis,
    FontVariant,
    FontVariantCaps,
    FontVariantEastAsian,
    FontVariantLigatures,
    FontVariantNumeric,
    FontVariantPosition,
    FontWeight,
    Gap,
    Globalcompositeoperation,
    GlyphOrientationVertical,
    Grid,
    GridArea,
    GridAutoColumns,
    GridAutoFlow,
    GridAutoRows,
    GridColumn,
    GridColumnEnd,
    GridColumnGap,
    GridColumnStart,
    GridGap,
    GridRow,
    GridRowEnd,
    GridRowGap,
    GridRowStart,
    GridTemplate,
    GridTemplateAreas,
    GridTemplateColumns,
    GridTemplateRows,
    HangingPunctuation,
    Height,
    Hyphens,
    ImageOrientation,
    ImageRendering,
    ImageResolution,
    Isolation,
    JustifyContent,
    JustifyItems,
    JustifySelf,
    Left,
    LetterSpacing,
    LightingColor,
    LineBreak,
    LineHeight,
    ListStyle,
    ListStyleImage,
    ListStylePosition,
    ListStyleType,
    Margin,
    MarginBottom,
    MarginLeft,
    MarginRight,
    MarginTop,
    Mask,
    MaskBorder,
    MaskBorderMode,
    MaskBorderOutset,
    MaskBorderRepeat,
    MaskBorderSlice,
    MaskBorderSource,
    MaskBorderWidth,
    MaskClip,
    MaskComposite,
    MaskImage,
    MaskMode,
    MaskOrigin,
    MaskPosition,
    MaskRepeat,
    MaskSize,
    MaskType,
    MaxHeight,
    MaxWidth,
    MinHeight,
    MinWidth,
    MixBlendMode,
    ObjectFit,
    ObjectPosition,
    Opacity,
    Order,
    Orphans,
    Outline,
    OutlineColor,
    OutlineOffset,
    OutlineStyle,
    OutlineWidth,
    Overflow,
    OverflowWrap,
    Padding,
    PaddingBottom,
    PaddingLeft,
    PaddingRight,
    PaddingTop,
    PageBreakAfter,
    PageBreakBefore,
    PageBreakInside,
    Pause,
    PauseAfter,
    PauseBefore,
    Pitch,
    PitchRange,
    PlaceContent,
    PlaceItems,
    PlaceSelf,
    PlayDuring,
    Position,
    Quotes,
    Resize,
    Rest,
    RestAfter,
    RestBefore,
    Richness,
    Right,
    RowGap,
    ScrollMargin,
    ScrollMarginBlock,
    ScrollMarginBlockEnd,
    ScrollMarginBlockStart,
    ScrollMarginBottom,
    ScrollMarginInline,
    ScrollMarginInlineEnd,
    ScrollMarginInlineStart,
    ScrollMarginLeft,
    ScrollMarginRight,
    ScrollMarginTop,
    ScrollPadding,
    ScrollPaddingBlock,
    ScrollPaddingBlockEnd,
    ScrollPaddingBlockStart,
    ScrollPaddingBottom,
    ScrollPaddingInline,
    ScrollPaddingInlineEnd,
    ScrollPaddingInlineStart,
    ScrollPaddingLeft,
    ScrollPaddingRight,
    ScrollPaddingTop,
    ScrollSnapAlign,
    ScrollSnapStop,
    ScrollSnapType,
    ShapeImageThreshold,
    ShapeMargin,
    ShapeOutside,
    Speak,
    SpeakAs,
    SpeakHeader,
    SpeakNumeral,
    SpeakPunctuation,
    SpeechRate,
    Stress,
    TableLayout,
    TabSize,
    TextAlign,
    TextAlignAll,
    TextAlignLast,
    TextCombineUpright,
    TextDecoration,
    TextDecorationColor,
    TextDecorationLine,
    TextDecorationStyle,
    TextEmphasis,
    TextEmphasisColor,
    TextEmphasisPosition,
    TextEmphasisStyle,
    TextIndent,
    TextJustify,
    TextOrientation,
    TextOverflow,
    TextShadow,
    TextTransform,
    TextUnderlinePosition,
    Top,
    Transform,
    TransformBox,
    TransformOrigin,
    Transition,
    TransitionDelay,
    TransitionDuration,
    TransitionProperty,
    TransitionTimingFunction,
    UnicodeBidi,
    VerticalAlign,
    Visibility,
    VoiceBalance,
    VoiceDuration,
    VoiceFamily,
    VoicePitch,
    VoiceRange,
    VoiceRate,
    VoiceStress,
    VoiceVolume,
    Volume,
    WhiteSpace,
    Widows,
    Width,
    WillChange,
    WordBreak,
    WordSpacing,
    WordWrap,
    WritingMode,
    ZIndex,
}


///////////////////////////////////////////////////////////////////////////////
// INTERNAL VALUE
///////////////////////////////////////////////////////////////////////////////

#[derive(Debug, Clone, PartialEq, PartialOrd, Eq, Ord, Hash)]
/// TODO:
/// * eemove all redundant length labels (in favor of unified Length enum)
pub enum Value {
    Length(Length),
    Length2(Length, Length),
    Length3(Length, Length, Length),
    Length4(Length, Length, Length, Length),
    RunIn,
    Flow,
    FlowRoot,
    Inline,
    Add,
    Additive,
    Alias,
    All,
    AllowEnd,
    AllScroll,
    Alpha,
    Alphabetic,
    Alternate,
    AlternateReverse,
    Always,
    Anywhere,
    ArabicIndic,
    Arithmetic,
    Armenian,
    Atop,
    Aural,
    Auto,
    AutoFill,
    AutoFit,
    Avoid,
    AvoidColumn,
    AvoidPage,
    AvoidRegion,
    Backgroundalpha,
    Backgroundimage,
    Backwards,
    Balance,
    BalanceAll,
    Baseline,
    Bengali,
    BidiOverride,
    Blink,
    Block,
    BorderBox,
    Both,
    Bottom,
    Braille,
    BreakAll,
    BreakSpaces,
    BreakWord,
    Bullets,
    Cambodian,
    Capitalize,
    Cell,
    Center,
    Ch,
    Circle,
    CjkDecimal,
    CjkEarthlyBranch,
    CjkHeavenlyStem,
    CjkIdeographic,
    Clip,
    Clone,
    CloseQuote,
    ClosestCorner,
    ClosestSide,
    Coarse,
    Color,
    ColorBurn,
    ColorDodge,
    ColResize,
    Column,
    ColumnReverse,
    Contain,
    Content,
    ContentBox,
    Contents,
    ContextMenu,
    Copy,
    Cover,
    CrispEdges,
    Crosshair,
    Currentcolor,
    Cyclic,
    Darken,
    Dashed,
    Decimal,
    DecimalLeadingZero,
    Default,
    Deg,
    Dense,
    Devanagari,
    Difference,
    Disc,
    DisclosureClosed,
    DisclosureOpen,
    Discrete,
    Distribute,
    Dot,
    Dotted,
    Double,
    DoubleCircle,
    Dpcm,
    Dpi,
    Dppx,
    Duplicate,
    EachLine,
    Ease,
    EaseIn,
    EaseInOut,
    EaseOut,
    Ellipse,
    Ellipsis,
    Embed,
    Embossed,
    End,
    EResize,
    EthiopicNumeric,
    Evenodd,
    EwResize,
    Ex,
    Exclude,
    Exclusion,
    Extends,
    FarthestCorner,
    FarthestSide,
    Fast,
    Fill,
    FillBox,
    Filled,
    Fillpaint,
    Fine,
    First,
    FitContent,
    Fixed,
    Flex,
    FlexEnd,
    FlexStart,
    FontFeatureSettings,
    FontVariant,
    ForceEnd,
    Forwards,
    Fr,
    FromImage,
    FullSizeKana,
    FullWidth,
    Gamma,
    Georgian,
    Grab,
    Grabbing,
    Grad,
    Grid,
    Groove,
    Gujarati,
    Gurmukhi,
    Handheld,
    Hanging,
    HardLight,
    Hebrew,
    Help,
    Hidden,
    HighQuality,
    Hiragana,
    HiraganaIroha,
    HorizontalTb,
    Hover,
    Hue,
    Hz,
    Identity,
    InterCharacter,
    Interlace,
    Intersect,
    InterWord,
    Invert,
    Isolate,
    IsolateOverride,
    JapaneseFormal,
    JapaneseInformal,
    JumpBoth,
    JumpEnd,
    JumpNone,
    JumpStart,
    Justify,
    JustifyAll,
    Kannada,
    Katakana,
    KatakanaIroha,
    KeepAll,
    Khmer,
    Khz,
    KoreanHangulFormal,
    KoreanHanjaFormal,
    KoreanHanjaInformal,
    Landscape,
    Lao,
    Last,
    Layout,
    Left,
    Legacy,
    Lighten,
    Linear,
    Linearrgb,
    LineThrough,
    ListItem,
    Local,
    Loose,
    LowerAlpha,
    LowerArmenian,
    Lowercase,
    LowerGreek,
    LowerLatin,
    LowerRoman,
    Ltr,
    Luminance,
    Luminosity,
    Malayalam,
    Mandatory,
    Manual,
    MarginBox,
    MatchParent,
    MatchSource,
    MaxContent,
    Medium,
    MinContent,
    Minmax,
    Mixed,
    Mm,
    Mongolian,
    Move,
    Ms,
    Multiply,
    Myanmar,
    NeResize,
    NeswResize,
    NoClip,
    NoCloseQuote,
    NoComposite,
    NoDrop,
    None,
    Nonzero,
    NoOpenQuote,
    NoRepeat,
    Normal,
    Not,
    NotAllowed,
    Nowrap,
    NResize,
    NsResize,
    Numbers,
    Numeric,
    NwResize,
    NwseResize,
    Objectboundingbox,
    Only,
    Open,
    OpenQuote,
    OptionalPaged,
    Oriya,
    Outset,
    Over,
    Overlay,
    Overline,
    P3,
    PaddingBox,
    Page,
    Paged,
    Paint,
    Paused,
    Pc,
    Persian,
    Pixelated,
    Pixel,
    Plaintext,
    Pointer,
    Portrait,
    Pre,
    PreLine,
    PreWrap,
    Print,
    Progress,
    Progressive,
    Projection,
    Proximity,
    Rec2020,
    Recto,
    Region,
    Repeat,
    RepeatX,
    RepeatY,
    Reverse,
    Revert,
    Ridge,
    Right,
    Rotate,
    Round,
    Row,
    RowResize,
    RowReverse,
    Rtl,
    Running,
    S,
    Safe,
    Saturation,
    Scale,
    ScaleDown,
    Scalex,
    Scaley,
    Screen,
    Scroll,
    ScrollPosition,
    SelfEnd,
    SelfStart,
    SeResize,
    Sesame,
    Sideways,
    SidewaysRight,
    SimpChineseFormal,
    SimpChineseInformal,
    Size,
    Skew,
    Skewx,
    Skewy,
    Slice,
    Slow,
    Smooth,
    SoftLight,
    Solid,
    Sourcealpha,
    Sourcegraphic,
    Space,
    SpaceAround,
    SpaceBetween,
    SpaceEvenly,
    Speech,
    SpellOut,
    Square,
    SResize,
    Srgb,
    Start,
    StepEnd,
    StepStart,
    Stretch,
    Strict,
    StrokeBox,
    Strokepaint,
    Style,
    Subtract,
    SwResize,
    Symbolic,
    Table,
    TableCaption,
    TableCell,
    TableColumn,
    TableColumnGroup,
    TableFooterGroup,
    TableHeaderGroup,
    TableRow,
    TableRowGroup,
    Tamil,
    Telugu,
    Text,
    Thai,
    Thick,
    Thin,
    Tibetan,
    Top,
    TradChineseFormal,
    TradChineseInformal,
    Translate,
    Translatex,
    Translatey,
    Triangle,
    Tty,
    Turn,
    Tv,
    Under,
    Underline,
    Unsafe,
    Unset,
    UpperAlpha,
    UpperArmenian,
    Uppercase,
    UpperLatin,
    UpperRoman,
    Upright,
    Userspaceonuse,
    Verso,
    VerticalLr,
    VerticalRl,
    VerticalText,
    Vh,
    ViewBox,
    Vmax,
    Vmin,
    Vw,
    Wait,
    Words,
    Wrap,
    WrapReverse,
    WResize,
    X,
    Xor,
    Y,
    ZoomIn,
    ZoomOut,
}


///////////////////////////////////////////////////////////////////////////////
// CUSTOM
///////////////////////////////////////////////////////////////////////////////


#[derive(Debug, Clone, PartialEq, PartialOrd, Eq, Ord, Hash)]
pub struct Url(pub String);

#[derive(Debug, Clone, PartialEq, PartialOrd, Eq, Ord, Hash)]
pub enum Angle {
    Deg,
    Rad,
    Grad,
    Turn,
}

#[derive(Debug, Clone, PartialEq, PartialOrd, Eq, Ord, Hash)]
pub enum Time {
    S(i32),
    Ms(i32)
}

#[derive(Debug, Clone, PartialEq, PartialOrd, Eq, Ord, Hash)]
pub enum Length {
    Px(Float),
    Rem(Float),
    Em(Float),
    Cm(Float),
    Pt(Float),
    Q(Float),
    Mm(Float),
    In(Float),
}

impl Length {
    pub fn px(x: impl Number) -> Self {
        Length::Px(x.normalize())
    }
    pub fn render_css_syntax(&self) -> String {
        unimplemented!()
    }
}




///////////////////////////////////////////////////////////////////////////////
// NUMBER
///////////////////////////////////////////////////////////////////////////////

pub trait Number {
    fn normalize(self) -> Float;
}
impl Number for f64 {
    fn normalize(self) -> Float {
        Float(self)
    }
}
impl Number for i32 {
    fn normalize(self) -> Float {
        Float(self as f64)
    }
}


#[derive(Debug, Clone, PartialOrd)]
pub struct Float(f64);

impl fmt::Display for Float {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}
impl Eq for Float {}
impl Ord for Float {
    fn cmp(&self, other: &Float) -> Ordering {
        self.0.partial_cmp(&other.0).unwrap_or(Ordering::Less)
    }
}
impl PartialEq for Float {
    fn eq(&self, other: &Float) -> bool {
        self.0 == other.0
    }
}
impl Hash for Float {
    fn hash<H: Hasher>(&self, state: &mut H) {
        let x = format!("{}", self.0);
        x.hash(state);
    }
}